name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/chaitanya70325

    - name: Login to dockerhub
      uses: docker/login-chai7278
      with:
       username: ${{ secrets.DOCKERHUB_chai7278}}
       password: ${{ secrets.DOCKERHUB_dckr_pat_9mK5ZDTbNQ7v7sDZfHKptRIZrc8 }}

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
       context:
       push: true
       tags: chaitanya70325/githubaction:latest
